examiz/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.auth
urlpatterns = [
	url(r'^', include('quiz.urls', namespace="quiz")),
	url(r'^admin/', include(admin.site.urls)),
	url('^', include('django.contrib.auth.urls')),
]

quiz/urls.py
from django.conf.urls import include, url
# from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^login/$', login, {'template_name':'accounts/login.html'}),
	url(r'logout$', logout, {'next_page': '/'}, name='logout'),
	url(r'^type_login/$', views.type_login, name='type_login'),

	#user side
	url(r'^user_home/$',views.user_home, name='user_home'),
	url(r'^register/$',views.register, name='register'),
	url(r'^all_assessments/$', views.all_assessments, name='all_assessments'),
	url(r'^apply_assessments/$', views.apply_assessments, name='apply_assessments'),
	url(r'^apply_assessments/(?P<assessment_no>\d+)/$', views.apply_request, name='apply_request'),
	url(r'^assessment_detail/(?P<assessment_no>\d+)/$',views.assessment_detail, name='assessment_detail'),
	url(r'^assessment_detail/(?P<assessment_no>\d+)/start$',views.assessment_start, name='assessment_start'),
	url(r'^assessment_detail/(?P<assessment_no>\d+)/(?P<question_no>\d+)$',views.assessment_start_question, name='assessment_start_question'),
	url(r'^assessment_finish/(?P<assessment_no>\d+)/$',views.assessment_finish, name='assessment_finish'),
	url(r'^assessment_finish/(?P<assessment_no>\d+)/submit$',views.assessment_finish_submit, name='assessment_finish_submit'),
	url(r'^assessment_finish/(?P<assessment_no>\d+)/time_exp/$',views.time_exp, name='time_exp'),
	url(r'^reset_password/$', password_reset, name='reset_password'),
	url(r'^reset_password/done/$', password_reset_done, name='password_reset_done'),
	url(r'^reset_password/complete/$', password_reset_complete, name='password_reset_complete'),
	url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name='password_reset_confirm'),

	#admin side
	url(r'^admin_home/$',views.admin_home, name='admin_home'),
	url(r'^register_reqs/$',views.register_reqs, name='register_reqs'),
	url(r'^register_students/$',views.register_students, name='register_students'),
	url(r'^approve/(?P<request_no>\d+)/$',views.approveRegister, name='approveRegister'), 
	url(r'^disapprove/(?P<request_no>\d+)/$',views.disapproveRegister, name='disapproveRegister'),
	url(r'^viewAssessmentStudents/(?P<assessment_no>\d+)/$',views.viewAssessmentStudents, name='viewAssessmentStudents'),
	url(r'^viewAssessmentStudents/(?P<assessment_no>\d+)/accept_all/$',views.accept_all_test_request, name='accept_all_test_request'),
	url(r'^viewAssessmentStudents/(?P<assessment_no>\d+)/accepted/$',views.accepted_test_request, name='accepted_test_request'),
	url(r'^viewAssessmentStudents/(?P<assessment_no>\d+)/(?P<user_no>\d+)/1$',views.accept_test_request, name='accept_test_request'),
	url(r'^viewAssessmentStudents/(?P<assessment_no>\d+)/(?P<user_no>\d+)/2$',views.reject_test_request, name='reject_test_request'),
	url(r'^assessment/$',views.assessment, name='assessment'),
	url(r'^create/$',views.createAssessment, name='createAssessment'),
	url(r'^view_assessment/(?P<assessment_no>\d+)/$',views.viewAssessment, name='viewAssessment'),
	url(r'^view_assessment/(?P<assessment_no>\d+)/edit/$',views.editAssessment, name='editAssessment'),
	url(r'^assessment_live/(?P<assessment_no>\d+)/$',views.assessment_live, name='assessment_live'),
	url(r'^create_question/(?P<assessment_no>\d+)/$',views.createQuestion, name='createQuestion'),
	url(r'^view_question/(?P<question_no>\d+)/$',views.viewQuestion, name='viewQuestion'),
	url(r'^view_question/(?P<question_no>\d+)/delete$',views.deleteQuestion, name='deleteQuestion'),
	url(r'^evaluation/$',views.evaluation, name='evaluation'),
	url(r'^evaluation/(?P<assessment_no>\d+)/$',views.assessment_evaluate, name='assessment_evaluate'),
	url(r'^evaluation/(?P<assessment_no>\d+)/download$',views.assessment_evaluate_download, name='assessment_evaluate_download'),
	url(r'^evaluation/(?P<assessment_no>\d+)/download_zip$',views.assessment_evaluate_user_answers, name='assessment_evaluate_user_answers'),
	url(r'^evaluation/(?P<assessment_no>\d+)/(?P<user_no>\d+)/$',views.assessment_evaluate_user, name='assessment_evaluate_user'),

]	

if True:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.admin.views.decorators import staff_member_required
import datetime
from django.utils import timezone
from .utils import emailSend, saveFile
import xlsxwriter, zipfile, os, shutil, random, urllib, xlrd
from django.http import HttpResponse, HttpResponseRedirect


def home(request):
	context={}
	return render(request, 'quiz/home.html', context)


def type_login(request):
	if(request.user.is_staff or request.user.is_superuser):
		return redirect('quiz:admin_home')
	else:
		return redirect('quiz:user_home')

def register(request):
	context={}
	if request.method=='POST':
		first_name=request.POST['first_name']
		last_name=request.POST['last_name']
		e_mail=request.POST['email']
		print(unicode(e_mail))
		print(User.objects.values_list('email'))
		for m in User.objects.values_list('email'):
			if unicode(e_mail)==m[0]:
				return render(request,'quiz/announcement.html', context={'message':"E-mail Address already exists."})
		print()
		password=request.POST['password']
		confirm_password=request.POST['confirm_password']
		if(password==confirm_password):
			my_uname=e_mail
			my_uname_array=my_uname.split('@')
			userName=my_uname_array[0]
			new_user=User.objects.create_user(userName,first_name=first_name, last_name=last_name, password=password, email=e_mail)
			email_message="Your Account has been created:\nUsername = "+userName
			emailSend("IIITD-Online Quiz 	Account Activation",e_mail,email_message)
			new_user.save()
			return render(request, 'quiz/announcement.html', context={'message':"User Created: Check your Email"})
		else:
			return render(request, 'quiz/announcement.html', context={'message':"Password Mismatch"})
	return render(request, 'quiz/register.html', context)


# Create User views here.

@login_required(login_url='/login')
def user_home(request):
	context={
	}
	return render(request, 'quiz/user_home.html', context)

@login_required(login_url='/login')
def apply_assessments(request):
	context={
		'all_assessments':Assessment.objects.filter(live=True),
	}
	return render(request, 'quiz/apply_assessments.html', context)

@login_required(login_url='/login')
def apply_request(request, assessment_no):
	assessment=get_object_or_404(Assessment, pk=assessment_no)
	user=request.user
	if assessment.pending_requests.filter(email=user.email).count()==0 and assessment.accecpted_requests.filter(email=user.email).count()==0:
		assessment.pending_requests.add(user)
		context={
			'message':'Request Registered',
		}
	elif assessment.pending_requests.filter(email=user.email).count()!=0:
		context={
		'message':'Request already Registered',
		}
	else:
		context={
		'message':'Request accecpted. You can now go to approved exams page.',
		}
	return render(request, 'quiz/announcement.html', context)

@login_required(login_url='/login')
def all_assessments(request):
	user=request.user
	all_assessments=Assessment.objects.filter(live=True)
	assessment_allowed=[]
	for assessment in all_assessments:
		if assessment.accecpted_requests.filter(email=user.email).count()!=0:
			assessment_allowed.append(assessment)
	context={
		'all_assessments':assessment_allowed,
	}
	return render(request, 'quiz/all_assessments.html', context)

@login_required(login_url='/login')
def assessment_detail(request, assessment_no):
	user=request.user
	assessment=get_object_or_404(Assessment, pk=assessment_no)
	context={
		'assessment':assessment,
	}
	if(not assessment.live  or assessment.accecpted_requests.filter(email=user.email).count()==0):
		return redirect('quiz:all_assessments')
	return render(request, 'quiz/assessment_detail.html',context)

@login_required(login_url='/login')
def assessment_start(request, assessment_no):
	assessment=get_object_or_404(Assessment, pk=assessment_no)
	if(not assessment.live):
		return redirect('quiz:all_assessments')
	questions=assessment.question_set.all()
	print(questions)
	now=datetime.datetime.now()
	end=now+datetime.timedelta(minutes=assessment.duration)
	if not Random_questions.objects.filter(user=request.user, assessment=assessment).exists():
		random_q=random.sample(list(range(questions.count())),assessment.no_of_questions)
		q=Random_questions(user=request.user,assessment=assessment)
		q.save()
		for i in random_q:
			q.random_ques.add(questions[i])
	questions_object=get_object_or_404(Random_questions,user=request.user,assessment=assessment)
	questions=questions_object.random_ques.all()
	if not timeRemaining.objects.filter(user=request.user, assessment=assessment).exists():
		t=timeRemaining(user=request.user, timeStart=now, timeEnd=end, assessment=assessment)
		t.save()
	return redirect('quiz:assessment_start_question', assessment.pk, questions[0].pk)

@login_required(login_url='/login')
def assessment_start_question(request, assessment_no, question_no):
	assessment=get_object_or_404(Assessment, pk=assessment_no)
	if(not assessment.live):
		return redirect('quiz:all_assessments')
	question=get_object_or_404(Question, pk=question_no)
	questions=assessment.question_set.all()
	if not Random_questions.objects.filter(user=request.user, assessment=assessment).exists():
		random_q=random.sample(list(range(questions.count())),assessment.no_of_questions)
		q=Random_questions(user=request.user,assessment=assessment)
		q.save()
		for i in random_q:
			q.random_ques.add(questions[i])
	questions_object=get_object_or_404(Random_questions,user=request.user,assessment=assessment)
	questions=questions_object.random_ques.all()
	flag=0
	next_question=question
	for i in questions:
		if(flag==1):
			next_question=i
			break
		if i==question:
			flag=1
	now=datetime.datetime.now()
	end=now+datetime.timedelta(minutes=assessment.duration)
	if not timeRemaining.objects.filter(user=request.user, assessment=assessment).exists():
		t=timeRemaining(user=request.user, timeStart=now, timeEnd=end, assessment=assessment)
		t.save()
	t=get_object_or_404(timeRemaining, user=request.user, assessment=assessment)
	now=t.timeStart
	end=t.timeEnd
	start_time=int(now.strftime("%s"))*1000
	end_time=int(end.strftime("%s"))*1000

	try:
		my_resp=Response.objects.get(question=question, assessment=assessment, user=request.user)
		my_resp=str(my_resp.response)
	except Response.DoesNotExist:
		my_resp='Z'
	
	if request.method=='POST':
		response=request.POST['optionsRadios']
		response_object=Response(
			user=request.user,
			assessment=assessment,
			question=question,
			response=response
		)
		try:
			prev_res=Response.objects.get(question=question, assessment=assessment, user=request.user)
			prev_res.response=response
		except Response.DoesNotExist:
			prev_res = response_object
		curr=datetime.datetime.now()
		if(timezone.now()<end):
			prev_res.save()
		else:
			return render(request, 'quiz/announcement.html', context={'message':"Time has expired!"})

		if(next_question==question):
			return redirect('quiz:assessment_finish', assessment.pk)
		return redirect('quiz:assessment_start_question', assessment.pk, next_question.pk)
	context={
		'questions':questions,
		'assessment':assessment,
		'start_time':start_time,
		'end_time':end_time,
		'curr_time':int(datetime.datetime.now().strftime("%s"))*1000,
		'question':question,
		'response':my_resp
	}
	return render(request, 'quiz/assessment_start.html', context)

@login_required(login_url='/login')
def assessment_finish(request, assessment_no):
	assessment=get_object_or_404(Assessment, pk=assessment_no)
	if(not assessment.live):
		return redirect('quiz:all_assessments')
	questions_object=get_object_or_404(Random_questions,user=request.user,assessment=assessment)
	questions=questions_object.random_ques.all()
	context={
		'assessment':assessment,
		'firstq':questions[0]
	}

	return render(request, 'quiz/assessment_finish.html', context)

@login_required(login_url='/login')
def assessment_finish_submit(request,assessment_no):
	assessment=get_object_or_404(Assessment, pk=assessment_no)
	if(not assessment.live):
		return redirect('quiz:all_assessments')
	if assessment.conformation_mail==0:
		pass
	elif assessment.conformation_mail==1:
		email_message="Your response to " + assessment.name + " is recorded. You will hear about your scores shortly."
		emailSend("IIITD Exam Portal",request.user.email,email_message)
	elif assessment.conformation_mail==2:
		user_responses=Response.objects.filter(assessment=assessment, user=request.user)
		score=0
		for response in user_responses:
			if(response.question.solution==response.response):
				score=score+1
		email_message="You scored " +str(score)+" in "+ assessment.name + " out of "+ assessment.no_of_questions
		emailSend("IIITD Exam Portal",request.user.email,email_message)
	return redirect('quiz:home')

@login_required(login_url='/login')
def time_exp(request,assessment_no):
	assessment=get_object_or_404(Assessment, pk=assessment_no)
	if(not assessment.live):
		return redirect('quiz:all_assessments')
	if assessment.conformation_mail==0:
		pass
	elif assessment.conformation_mail==1:
		email_message="Your response to " + assessment.name + " is recorded. You will hear about your scores shortly."
		emailSend("IIITD Exam Portal",request.user.email,email_message)
	elif assessment.conformation_mail==2:
		user_responses=Response.objects.filter(assessment=assessment, user=request.user)
		score=0
		for response in user_responses:
			if(response.question.solution==response.response):
				score=score+1
		email_message="You scored " +str(score)+" in "+ assessment.name + " out of "+ assessment.no_of_questions
		emailSend("IIITD Exam Portal",request.user.email,email_message)
	context={}
	return render(request, 'quiz/time_expired.html', context)
# Create Admin views here.

@staff_member_required
def admin_home(request):
	user=request.user

	status='Staff'
	context={
	'status':status,
	'user':user,
	}

quiz/templates/quiz/all_assessments.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block title%}All Assessments{% endblock %}
{% block body %}
<style type="text/css">
	.panel{
		height: 100px;
		vertical-align: middle;
	}
</style>
<div class="container">
	<h3>Assessments</h3>
	<hr>
	{% for assessment in all_assessments %}
		<div class="col-sm-3">
			<a href="{% url 'quiz:assessment_detail' assessment.pk%}">
			<div class="panel panel-default">
				<h4><center>{{assessment.name}}</center></h4>
			</div>
			</a>
		</div>
	{% endfor %}
</div>

{% endblock %}

quiz/templates/quiz/assessment.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block title%}create{% endblock %}
{% block body %}
<style type="text/css">
	.panel{
		height: 100px;
		vertical-align: middle;
	}
</style>
<div class="container">
	<h3>Assessments</h3>
	<hr>
	<div class="col-sm-3">
		<a href="{% url 'quiz:createAssessment'%}">
		<div class="panel panel-default">
		<h1><center>
			<span class="glyphicon glyphicon-plus"></span>
		</center></h1>
		</div>
		</a>
	</div>
	{% for assessment in assessments %}
		<div class="col-sm-3">
			<a href="{% url 'quiz:viewAssessment' assessment.pk%}">
			<div class="panel panel-default">
				<h4><center>{{assessment.name}}</center></h4>
			</div>
			</a>
		</div>
	{% endfor %}
</div>

{% endblock %}

quiz/templates/quiz/assessment_evaluate.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block title%}Evaluation{% endblock %}
{% block body %}

<div class="container">
	<h3>Appearing Students</h3>
	<hr>
	<p><a href="{% url 'quiz:assessment_evaluate_download' assessment.pk %}">Click here</a> to download marks.</p>
	<p><a href="{% url 'quiz:assessment_evaluate_user_answers' assessment.pk %}">Click here</a> to download all student's responses.</p>
	<table class="table table-bordered">
	<thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Marks</th>
      </tr>
    </thead>
    <tbody>
	{% for user,marks in users_marks %}
	<tr>
      	<td>
			<a href="{% url 'quiz:assessment_evaluate_user' assessment.pk user.pk%}">
				{{user.first_name}} {{user.last_name}}
			</a>
		</td>
		<td>
			{{user.email}}
		</td>
		<td>
			{{marks}}
		</td>
	</tr>

	{% endfor %}
</tbody>
  </table>
</div>

{% endblock %}

quiz/templates/quiz/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <meta name="description" content="">
    <meta name="author" content=""> -->
    <!-- <link rel="icon" href="../../favicon.ico"> -->

    <title>Assessments-{% block title %}{% endblock %}</title>

    {% load staticfiles %}
    <link rel="icon" href="{% static 'quiz/images/logowith.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="{% static 'quiz/css/base.css' %}" rel="stylesheet">
  </head>
  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'quiz:home' %}"><b>IIITD</b> | Assessments</a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'quiz:type_login' %}">Home</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
              <li><a href="{% url 'quiz:logout' %}">Logout</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block body %}
    {% endblock %}

    </div>
    <footer class="footer">
      <div class="container">
      <br>
          <p>Developed By <a  style="color: #000;" href="https://github.com/mayankmtg">Mayank Mohindra</a> @ 
          <a  style="color: #000;" href="https://iiitd.ac.in/">IIITD</a>
        <br></p>
      </div>
    </footer>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

quiz/templates/quiz/home.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block title%}Home{% endblock %}
{% block body %}

<br>
<div class="container">
	<div class="row">
		<div class="col-sm-5 pull-left">
		<div class="pull-right">
		<br>
			<img src="{% static 'quiz/images/logowithout.png' %}" height="320px">

		</div>
		</div>
		<div class="col-sm-1">
			&nbsp;
		</div>
		<div class="col-sm-6 pull-right">
		<div class="pull-left">
			<br>
			<h1 style="font-size: 50px">Online<br> </h1>
			<h1 style="font-size: 50px">Assessment<br></h1>
			<h1>Portal of IIIT-Delhi</h1>
			<br>
			{% if not request.user.is_authenticated %}
				<a href="/login/" class="button">LogIn</a>
				<a class="button" href="{% url 'quiz:register' %}">New User</a>
			{% else %}
				<a href="{% url 'quiz:type_login' %}" class="button">Home</a>
			{% endif %}
		</div>
		</div>
	</div>
	<br><br>
	<hr>
	<br><br>
	<!-- 
	<div class="col-xs-9">
		<div class="jumbotron">
			<h2>About the Portal</h2>
			<p>This is a template showcasing the optional theme stylesheet included in Bootstrap. Use it as a starting point to create something more unique by building on or modifying it.</p>
		</div>
	</div>
	<div class="col-xs-3">
		<div class="list-group">
			<a href="#" class="list-group-item active center">
			Important Links
			</a>
			<a href="#" class="list-group-item center">Link 1</a>
			<a href="#" class="list-group-item center">Link 2</a>
			<a href="#" class="list-group-item center">Link 3</a>
		</div>
	</div>
	<div class="col-xs-3">
		<div class="list-group">
			<a href="#" class="list-group-item active center">
			Announcements
			</a>
			<a href="#" class="list-group-item center">No new Announcements</a>
		</div>
	</div>
 	-->
</div>

{% endblock %}

quiz/templates/quiz/register_reqs.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block title %}Auth{% endblock %}
{% block body %}
<div class="container">
	<center><h1>User Requests</h1></center>
	<br>

	<table class="table table-striped">
		<tr>
			<th>Request_Number</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>E-Mail Address</th>
			<th>Approve</th>
			<th>Dis-Approve</th>
		</tr>
		{% for request in register_reqs %}
		<tr>
			<td>{{ request.pk }}</td>
			<td>{{ request.first_name }}</td>
			<td>{{ request.last_name }}</td>
			<td>{{ request.e_mail }}</td>
			<td><a href="{% url 'quiz:approveRegister' request.pk %}">Approve</a></td>
			<td><a href="{% url 'quiz:disapproveRegister' request.pk %}">Dis-Approve</a></td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}

quiz/templates/quiz/time_expired.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block title%}Details{% endblock %}
{% block body %}
<style type="text/css">
	.panel{
		height: 100px;
		vertical-align: middle;
	}
</style>
<div class="container">
	<center>
		<h1>Time Up</h1>
		<br>
		<h2>Your rresponses have been recorded </h2>
		<br>
		<h3><a href="{% url 'quiz:type_login' %}">Home</a></h3>
		<br>
		<h4>or</h4>
		<br>
		<h3><a href="{% url 'quiz:logout' %}">Logout</a></h3>
		
	</center>
</div>

{% endblock %}

quiz/templates/quiz/viewAssessmentStudents.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block title%}Evaluation{% endblock %}
{% block body %}


<div class="container">
	<h3>Pending requests</h3>
	<form class="form-horizontal" method="POST" action=""  enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-sm-4">Upload excel sheet to accept requests:-</label>
                <div class="col-sm-8">
                    <input type="file" name="excelfile">
                        <div class="col-sm-6">
                            <button type="submit">Submit</button>
                        </div>
                </div>
           </div>
    </form>
            <br>
	To accept all requests<a href="{% url 'quiz:accept_all_test_request' assessment.pk%}"> Click here.</a><br>
        To look at all accepted requests <a href="{% url 'quiz:accepted_test_request' assessment.pk%}">Click here.</a>
	<table class="table table-bordered">
	<thead>
      <tr>
        <th>Name</th>
        <th>Accept</th>
        <th>Decline</th>
      </tr>
    </thead>
    <tbody>
    	{% for user in pending_requests %}
    	<tr>
    		<td>{{user.first_name}} {{user.last_name}}</td>
            
    		<td><a href="{% url 'quiz:accept_test_request' assessment.pk user.pk%}">Accept</a></td>
    		<td><a href="{% url 'quiz:reject_test_request' assessment.pk user.pk%}">Decline</a></td>
    	</tr>
    	{% endfor %}
    </tbody>

</div>
{% endblock %}

quiz/templates/quiz/view_assessment.html
{% extends 'quiz/base.html' %}
{% load staticfiles %}
{% block title%}create{% endblock %}
{% block body %}
<style type="text/css">
	.panel{
		height: 100px;
		vertical-align: middle;
	}
</style>
<div class="container">
	<a href="{% url 'quiz:editAssessment' assessment.pk %}" class="btn btn-lg btn-success success">Edit Details</a>
	<center>
		<h3>{{assessment.name}}</h3>
		<h5>{{assessment.date}}</h5>
	</center>
	<br>
	<div class="row">
		<div class="col-sm-4"><b>Max Marks:</b>{{assessment.max_marks}}</div>
		<div class="col-sm-4"><center><b>No. of Questions:</b>{{assessment.no_of_questions}}</center></div>
		<div class="col-sm-4"><div class="pull-right"><b>Duration:</b>{{assessment.duration}}</div></div>
	</div>

	<center>
		{% if assessment.live %}
			<a href="{% url 'quiz:assessment_live' assessment.pk %}" class="btn btn-lg btn-success success">End Assessment</a>
		{% else %}
			<a href="{% url 'quiz:assessment_live' assessment.pk %}" class="btn btn-lg btn-success success">Go Live</a>
		{% endif %}
	</center>
	<br>
	{{ assessment.description }}
	<br>
	<center>
		<h3>Questions</h3>
	</center>
	<div class="col-sm-3">
		<a href="{% url 'quiz:createQuestion' assessment.pk%}">
		<div class="panel panel-default">
		<h1><center>
			<span class="glyphicon glyphicon-plus"></span>
		</center></h1>
		</div>
		</a>
	</div>
	{% for question in questions %}
		<div class="col-sm-3">
			<a href="{% url 'quiz:viewQuestion' question.pk%}">
			<div class="panel panel-default">
				{{question.question}}
			</div>
			</a>
		</div>
	{% endfor %}

</div>

{% endblock %}